title: Specialties
text: I administer individual and couple’s psychotherapy for adult and 
      adolescent populations struggling with mental health issues, as well as
      provide psychological testing for adult and adolescent populations.
section: services
list:
    - title: Diagnostic evaluations
      desc: To diagnose and discover what underlying mental health issues a person is
        experiencing and struggling with that interferes with their daily
        functioning in a variety of domains.  These include but are not limited
        to occupational, school, as well as interpersonal relationships.
      icon: fas fa-lightbulb
    - title: Crisis Interventions
      desc: To identify and aid individuals who are experiencing a crisis in their
        life that negatively impacts overall functioning, and to help improve
        their level of functioning by processing feelings and teaching effective
        coping strategies that allow the individual to manage their situation in
        a more effective manner.
      icon: fas fa-cloud-showers-heavy
    - title: Psychotherapy
      desc: Talk therapy is when an individual or couple work with a professional
        clinician in order to identify, discuss, and process mental health
        issues that are negatively impacting a person’s daily life functioning
        and/or relationships.  This process is facilitated in a safe space where
        the client(s) can learn to develop effective coping skills that will
        allow them to manage and reduce maladaptive thoughts, emotions, and
        behaviors.
      icon: fas fa-users